---
- hosts: localhost
  become: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2
    - name: Cloning the private repository 
      git: repo=ssh://git@github.com/wonchaitanya/Test.git  dest=/tmp 
    - name: copy test file
      copy: src=/tmp/Test/index.html dest=/var/www/html/
      notify:
         - restart apache2 

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
